version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      actions-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      dev-tools:
        dependency-type: "development"
    ignore:
      - dependency-name: "*"
        versions:
          - "<= 999.0.0"
